### ISSUE TITLE
Actor movement inconsistent

### ISSUE THREAD

**Issue by jhenriquelc** [ItzJaum/coords-py#1]
sometimes it moves two or not at all when sending Actor.move(direction) and I still don't get how.
described more in-depth in [stackoverflow](https://stackoverflow.com/questions/65907280/variable-1-in-python-function-adding-incorrectly-by-2)

**Comment by ItzJaum** [comment]
Fixed by commit 6f4d879251f2a6f493e0773fef2baecad7ce1d14

**Comment by jhenriquelc** [comment]
fixed by 6f4d879251f2a6f493e0773fef2baecad7ce1d14
